# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deletUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QMessageBox

connect = mysql.connector.connect(
    host='db3.super10.com.br',
    user='ludwig.gonzaga',
    password='61u7Mfy&iS#x',
    database='tests'
)


class Ui_userExclude(object):
    def setupUi(self, userExclude):
        userExclude.setObjectName("userExclude")
        userExclude.resize(1020, 750)
        userExclude.setMinimumSize(QtCore.QSize(1020, 750))
        userExclude.setMaximumSize(QtCore.QSize(1050, 900))
        self.labelTitulo = QtWidgets.QLabel(userExclude)
        self.labelTitulo.setGeometry(QtCore.QRect(10, 10, 1001, 81))
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelFindMail = QtWidgets.QLabel(userExclude)
        self.labelFindMail.setGeometry(QtCore.QRect(40, 100, 81, 51))
        self.labelFindMail.setObjectName("labelFindMail")
        self.findMail = QtWidgets.QLineEdit(userExclude)
        self.findMail.setGeometry(QtCore.QRect(130, 110, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.findMail.setFont(font)
        self.findMail.setObjectName("findMail")
        self.labelTitulo2 = QtWidgets.QLabel(userExclude)
        self.labelTitulo2.setGeometry(QtCore.QRect(10, 180, 1001, 81))
        self.labelTitulo2.setObjectName("labelTitulo2")
        self.labelIduser = QtWidgets.QLabel(userExclude)
        self.labelIduser.setGeometry(QtCore.QRect(30, 280, 101, 51))
        self.labelIduser.setObjectName("labelIduser")
        self.delIduser = QtWidgets.QLineEdit(userExclude)
        self.delIduser.setGeometry(QtCore.QRect(150, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delIduser.setFont(font)
        self.delIduser.setObjectName("delIduser")
        self.delName = QtWidgets.QLineEdit(userExclude)
        self.delName.setGeometry(QtCore.QRect(400, 290, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delName.setFont(font)
        self.delName.setObjectName("delName")
        self.labelFindName = QtWidgets.QLabel(userExclude)
        self.labelFindName.setGeometry(QtCore.QRect(280, 280, 101, 51))
        self.labelFindName.setObjectName("labelFindName")
        self.delEmail = QtWidgets.QLineEdit(userExclude)
        self.delEmail.setGeometry(QtCore.QRect(200, 370, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delEmail.setFont(font)
        self.delEmail.setObjectName("delEmail")
        self.labelMail = QtWidgets.QLabel(userExclude)
        self.labelMail.setGeometry(QtCore.QRect(80, 360, 101, 51))
        self.labelMail.setObjectName("labelMail")
        self.btnFind = QtWidgets.QPushButton(userExclude)
        self.btnFind.setGeometry(QtCore.QRect(764, 110, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnFind.setFont(font)
        self.btnFind.setObjectName("btnFind")
        self.labelTitulo3 = QtWidgets.QLabel(userExclude)
        self.labelTitulo3.setGeometry(QtCore.QRect(10, 420, 981, 151))
        self.labelTitulo3.setObjectName("labelTitulo3")
        self.btnExcluir = QtWidgets.QPushButton(userExclude)
        self.btnExcluir.setGeometry(QtCore.QRect(440, 570, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnExcluir.setFont(font)
        self.btnExcluir.setObjectName("btnExcluir")
        self.btnSair = QtWidgets.QPushButton(userExclude)
        self.btnSair.setGeometry(QtCore.QRect(440, 670, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnSair.setFont(font)
        self.btnSair.setObjectName("btnSair")

        self.retranslateUi(userExclude)
        self.btnSair.clicked.connect(userExclude.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(userExclude)
        self.btnFind.clicked.connect(self.findUser)
        self.btnExcluir.clicked.connect(self.excludeUser)

    def retranslateUi(self, userExclude):
        _translate = QtCore.QCoreApplication.translate
        userExclude.setWindowTitle(_translate("userExclude", "Excluir Usuário"))
        self.labelTitulo.setText(_translate("userExclude",
                                            "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">EXCLUIR USUÁRIO</span></p></body></html>"))
        self.labelFindMail.setText(_translate("userExclude",
                                              "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">E-mail:</span></p></body></html>"))
        self.labelTitulo2.setText(_translate("userExclude",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">USUÁRIO LOCALIZADO</span></p></body></html>"))
        self.labelIduser.setText(_translate("userExclude",
                                            "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">IDUSER: </span></p></body></html>"))
        self.labelFindName.setText(_translate("userExclude",
                                              "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">NOME: </span></p></body></html>"))
        self.labelMail.setText(_translate("userExclude",
                                          "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">E-MAIL: </span></p></body></html>"))
        self.btnFind.setText(_translate("userExclude", "Buscar"))
        self.labelTitulo3.setText(_translate("userExclude",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#e60004;\">ESSA AÇÃO É PERMANENTE E NÃO TEM COMO SER DESFEITA<br/>DESEJA CONTINUAR ?</span></p></body></html>"))
        self.btnExcluir.setText(_translate("userExclude", "EXCLUIR"))
        self.btnSair.setText(_translate("userExclude", "SAIR"))

    def findUser(self):
        usuario = []

        self.email = str(self.findMail.text())

        cursor = connect.cursor()

        comando = f'SELECT * FROM user WHERE email = "{self.email}";'
        cursor.execute(comando)
        usuario = cursor.fetchall()

        self.iduser = str(usuario[0][0])
        self.name = str(usuario[0][1])
        self.password = str(usuario[0][2])
        self.email = str(usuario[0][3])

        self.delIduser.setText(self.iduser)
        self.delName.setText(self.name)
        self.delEmail.setText(self.email)

        if (usuario != 0):
            print("Usuário localizado")

        else:
            print("Usuário não localizado.")

        cursor.close()

    def excludeUser(self):
        print("Clicado em excluir!")
        print("hello world")
        print("Me livrei da maldição")
        print(self.email)

        cursor = connect.cursor()

        comando = f'DELETE FROM user WHERE email = "{self.email}";'
        cursor.execute(comando)
        connect.commit()

        cursor.close()

        msg = QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle("Usuário excluído")
        msg.setText("O usuário:  " + self.name + " foi excluído.")
        msg.exec()

if __name__ == "__main__":


    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_userExclude()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())