# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

connect = mysql.connector.connect(
    host='db3.super10.com.br',
    user='ludwig.gonzaga',
    password='61u7Mfy&iS#x',
    database='tests'
)

class Ui_listAllUsers(object):
    def setupUi(self, listAllUsers):
        listAllUsers.setObjectName("listAllUsers")
        listAllUsers.resize(1020, 800)
        self.labelTitulo = QtWidgets.QLabel(listAllUsers)
        self.labelTitulo.setGeometry(QtCore.QRect(6, 10, 1001, 51))
        self.labelTitulo.setObjectName("labelTitulo")
        self.tableAllUsers = QtWidgets.QTableWidget(listAllUsers)
        self.tableAllUsers.setGeometry(QtCore.QRect(10, 60, 1001, 631))
        self.tableAllUsers.setAlternatingRowColors(True)
        self.tableAllUsers.setWordWrap(False)
        self.tableAllUsers.setObjectName("tableAllUsers")
        # self.tableAllUsers.setColumnCount(5)
        self.tableAllUsers.setColumnCount(4)
        self.tableAllUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUsers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUsers.setHorizontalHeaderItem(4, item)
        self.btnListar = QtWidgets.QPushButton(listAllUsers)
        self.btnListar.setGeometry(QtCore.QRect(60, 730, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnListar.setFont(font)
        self.btnListar.setObjectName("btnListar")
        self.btnSair = QtWidgets.QPushButton(listAllUsers)
        self.btnSair.setGeometry(QtCore.QRect(830, 730, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnSair.setFont(font)
        self.btnSair.setObjectName("btnSair")

        self.retranslateUi(listAllUsers)
        self.btnSair.clicked.connect(listAllUsers.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(listAllUsers)
        self.btnListar.clicked.connect(self.listar)

    def retranslateUi(self, listAllUsers):
        _translate = QtCore.QCoreApplication.translate
        listAllUsers.setWindowTitle(_translate("listAllUsers", "Listar todos usuários"))
        self.labelTitulo.setText(_translate("listAllUsers", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">LISTAS DE USUÁRIOS</span></p></body></html>"))
        item = self.tableAllUsers.horizontalHeaderItem(0)
        item.setText(_translate("listAllUsers", "ID"))
        item = self.tableAllUsers.horizontalHeaderItem(1)
        item.setText(_translate("listAllUsers", "Nome"))
        # item = self.tableAllUsers.horizontalHeaderItem(2)
        # item.setText(_translate("listAllUsers", "Senha"))
        item = self.tableAllUsers.horizontalHeaderItem(2)
        item.setText(_translate("listAllUsers", "E-mail"))
        item = self.tableAllUsers.horizontalHeaderItem(3)
        item.setText(_translate("listAllUsers", "URL Photo"))
        self.btnListar.setText(_translate("listAllUsers", "Listar"))
        self.btnSair.setText(_translate("listAllUsers", "Sair"))

    def listar(self):

           usuarios = []

           cursor = connect.cursor()

           comando = f'SELECT iduser, name , email , url_photo FROM user;'
           cursor.execute(comando)
           usuarios = cursor.fetchall()
           self.tableAllUsers.setRowCount(len(usuarios))
           self.tableAllUsers.setColumnCount(4)
           if (usuarios != 0):
               print("Usuários localizados")
               for i in range(0, len(usuarios)):
                   for j in range(0, 4):
                       self.tableAllUsers.setItem(i, j, QtWidgets.QTableWidgetItem(str(usuarios[i][j])))
           else:
               print("Usuários não localizados.")

           cursor.close()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_listAllUsers()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())