# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(530, 460)
        self.telaInicial = QtWidgets.QWidget(mainWindow)
        self.telaInicial.setObjectName("telaInicial")
        self.btnNewUser = QtWidgets.QPushButton(self.telaInicial)
        self.btnNewUser.setGeometry(QtCore.QRect(90, 100, 341, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewUser.setFont(font)
        self.btnNewUser.setObjectName("btnNewUser")
        self.labelTitle = QtWidgets.QLabel(self.telaInicial)
        self.labelTitle.setGeometry(QtCore.QRect(6, 10, 511, 81))
        self.labelTitle.setObjectName("labelTitle")
        self.btnListAll = QtWidgets.QPushButton(self.telaInicial)
        self.btnListAll.setGeometry(QtCore.QRect(90, 170, 341, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnListAll.setFont(font)
        self.btnListAll.setObjectName("btnListAll")
        self.btnUpdateUser = QtWidgets.QPushButton(self.telaInicial)
        self.btnUpdateUser.setGeometry(QtCore.QRect(89, 240, 341, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateUser.setFont(font)
        self.btnUpdateUser.setObjectName("btnUpdateUser")
        self.btnDeleteUser = QtWidgets.QPushButton(self.telaInicial)
        self.btnDeleteUser.setGeometry(QtCore.QRect(89, 310, 341, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnDeleteUser.setFont(font)
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.btnExit = QtWidgets.QPushButton(self.telaInicial)
        self.btnExit.setGeometry(QtCore.QRect(89, 380, 341, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        mainWindow.setCentralWidget(self.telaInicial)

        self.retranslateUi(mainWindow)
        self.btnExit.clicked.connect(mainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        self.btnNewUser.clicked.connect(self.windowNewUser)
        self.btnListAll.clicked.connect(self.windowListAll)
        self.btnUpdateUser.clicked.connect(self.windowUpdateUser)
        self.btnDeleteUser.clicked.connect(self.windowDeleteUser)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Gerenciamento de Usuários"))
        self.btnNewUser.setText(_translate("mainWindow", "CADASTRAR USUÁRIO"))
        self.labelTitle.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Gestão de usuários</span></p></body></html>"))
        self.btnListAll.setText(_translate("mainWindow", "LISTAR TODOS USUÁRIOS"))
        self.btnUpdateUser.setText(_translate("mainWindow", "EDITAR UM USUÁRIO"))
        self.btnDeleteUser.setText(_translate("mainWindow", "EXCLUIR UM USUÁRIO"))
        self.btnExit.setText(_translate("mainWindow", "FECHAR"))

    def windowNewUser(self):

        from newUser import Ui_newUser
        self.window = QtWidgets.QMainWindow()
        self.newUser = Ui_newUser()
        self.newUser.setupUi(self.window)
        self.window.show()
        print("novo usuário2")
        print("------------------------")

    def windowListAll(self):

        from listAll import Ui_listAllUsers
        self.window = QtWidgets.QMainWindow()
        self.listAll = Ui_listAllUsers()
        self.listAll.setupUi(self.window)
        self.window.show()
        print("listar todos os usuários")
        print("------------------------")

    def windowUpdateUser(self):

        from updateUser import Ui_updateUser
        self.window = QtWidgets.QMainWindow()
        self.updateUser = Ui_updateUser()
        self.updateUser.setupUi(self.window)
        self.window.show()
        print("editar usuário")
        print("------------------------")

    def windowDeleteUser(self):

        from deletUser import Ui_userExclude
        self.window = QtWidgets.QMainWindow()
        self.deleteUser = Ui_userExclude()
        self.deleteUser.setupUi(self.window)
        self.window.show()
        print("deletar usuário")
        print("------------------------")

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())